language: php
php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - vendor
    - $HOME/.composer

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--optimize-autoloader --no-progress"
    - COMPOSER_NO_INTERACTION=1

before_script:
  - composer global show hirak/prestissimo -q || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo
  - travis_retry composer install
  - travis_retry phpenv rehash

stages:
  - Static Code Analysis
  - Test

jobs:
  include:
    - stage: Static Code Analysis
      php: 7.3
      script:
        - vendor/bin/php-cs-fixer fix -v --dry-run

script:
  - vendor/bin/phpunit
